Switch to picocolors
hexojs/hexo-log pull request #67
Opened 2021-11-24 11:45 UTC by tomap

nanocolors is deprecated
+ cleanup co (switch to node 14 for coverage and linting)
+ add dependabot for github actions

2021-11-24 11:57 UTC, SukkaW approved these changes

2021-11-24 12:02 UTC, SukkaW requested changes
Would you mind splitting changes into 2 PRs? This PR introduces two changes.

Also, just changing `package.json` only is not enough.

2022-01-08 08:07 UTC, tomap commented
I used this PR to cleanup ci
Will do another one for nanocolors

2022-02-04 13:09 UTC, yoshinorin approved these changes
LGTM :)

2022-02-04 20:59 UTC, merged